[install]
# Use the fastest package manager
# registry = "https://registry.npmjs.org/"

[run]
# Enable experimental features for better performance
experimental = true

[test]
# Enable test runner optimizations
coverage = true

[dev]
# Enable hot reloading for development
hot = true